name: "Build the PHAR"
description: "Build the PHAR for the current commit"

runs:
    using: "composite"
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: "8.3"
              tools: castor

        - name: Compile PHAR
          run: castor phar:compile
          shell: bash

        - name: Ensure PHAR is OK
          run: build/jolitypo.phar --version
          shell: bash
          working-directory: tools/phar
