name: Continuous Integration

"on":
    push:
        branches:
            - main
    pull_request: ~

jobs:
    check-cs:
        name: Check Coding Standards
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                persist-credentials: false

            - name: Setup Castor
              uses: castor-php/setup-castor@2a495b8c91f00be6768ad8a040ba8634c797d386 # v1.1.0

            - name: Run CS check
              run: castor cs --dry-run

    phpstan:
        name: Static Analysis
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                persist-credentials: false

            - name: Setup Castor
              uses: castor-php/setup-castor@2a495b8c91f00be6768ad8a040ba8634c797d386 # v1.1.0

            - name: Install dependencies
              run: castor install

            - name: Run PHPStan
              run: castor phpstan

    ci:
        name: Test PHP ${{ matrix.php-version }} ${{ matrix.name }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version:
                    - "8.4"
                    - "8.5"
                composer-flags: [""]
                name: [""]
                include:
                    - php-version: 8.3
                      composer-flags: "--prefer-lowest"
                      name: "(prefer lowest dependencies)"

        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                persist-credentials: false

            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  php-version: "${{ matrix.php-version }}"

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Install dependencies
              run: composer update --prefer-dist --no-progress ${{ matrix.composer-flags }}

            - name: Run tests
              run: composer test
