name: Continuous Integration

"on":
    push:
        branches:
            - master
    pull_request: ~

jobs:
    ci:
        name: Test PHP ${{ matrix.php-version }} ${{ matrix.name }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version:
                    - "8.4"
                    - "8.5"
                composer-flags: [""]
                name: [""]
                include:
                    - php-version: 8.3
                      composer-flags: "--prefer-lowest"
                      name: "(prefer lowest dependencies)"

        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
              with:
                persist-credentials: false

            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  php-version: "${{ matrix.php-version }}"

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run tests
              run: composer test
