name: CI/CD

'on':
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request: null

jobs:
  ci:
    name: Run the test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.13.0
        with:
          php-version: '${{ matrix.php-versions }}'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: composer test

  phar:
    name: Create a PHAR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.13.0
        with:
          php-version: '${{ matrix.php-versions }}'

      - name: Install dependencies (lib)
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader --classmap-authoritative

      - name: Install dependencies (PHAR builder)
        run: composer install --prefer-dist --no-progress --optimize-autoloader --classmap-authoritative
        working-directory: tools/phar

      - name: Compile PHAR
        run: vendor/bin/box compile
        working-directory: tools/phar

      - name: Ensure PHAR is OK
        run: build/jolitypo.phar fr_FR README.md
        working-directory: tools/phar

      - name: Rename PHAR
        run: mv jolitypo.phar jolitypo-${{ matrix.php-versions }}.phar
        working-directory: tools/phar/build/

      - name: Upload PHAR
        uses: actions/upload-artifact@v2
        with:
          name: 'jolitypo-${{ matrix.php-versions }}'
          path: tools/phar/build/jolitypo-${{ matrix.php-versions }}.phar
          if-no-files-found: error

  release:
    if: '${{ startsWith(github.ref, ''refs/tags/v'') }}'
    name: Create a release
    runs-on: ubuntu-latest
    needs:
      - ci
      - phar

    steps:
      - name: Download PHAR
        uses: actions/download-artifact@v3

      - name: Move all PHAR is the current directory
        # see https://github.com/actions/download-artifact#download-all-artifacts
        run: mv jolitypo*/* .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: jolitypo-*.phar
